const coinList = ["ETHBTC","ADABTC","ONGBTC","LINKBTC","XRPBTC","ZECBTC","ZILBTC","BATBTC",
"ANKRBTC","XMRBTC","EOSBTC","KNCBTC","MATICBTC","BCDBTC","ONTBTC","EDOBTC","ATOMBTC","LTCBTC","XTZBTC","TRXBTC",
"KAVABTC","ERDBTC","OGNBTC","XVGBTC","DGBBTC","XLMBTC","OAXBTC","RENBTC","BNTBTC","IOSTBTC","SOLBTC","CHRBTC","VETBTC",
"ETCBTC","ZRXBTC","THETABTC","DASHBTC","LENDBTC","RVNBTC","LTOBTC","HBARBTC","ENJBTC","OMGBTC","GASBTC","NEOBTC",
"NULSBTC","MCOBTC","ALGOBTC","QKCBTC","SCBTC","RLCBTC","REPBTC","CELRBTC","WRXBTC","NASBTC","ONEBTC","CTSIBTC",
"TOMOBTC","QTUMBTC","DREPBTC","COTIBTC","IOTABTC","REQBTC","TNBBTC","POEBTC","BEAMBTC","ADXBTC","AMBBTC","LRCBTC",
"HIVEBTC","TROYBTC","IRISBTC","AIONBTC","IOTXBTC","POWRBTC","TFUELBTC","GOBTC","NKNBTC","STEEMBTC","CTXCBTC","QLCBTC",
"CHZBTC","GVTBTC","STMXBTC","BANDBTC","FUNBTC","SKYBTC","LOOMBTC","CMTBTC","ICXBTC","POLYBTC",
"FTMBTC","NANOBTC","ARKBTC","BTSBTC","BLZBTC","ASTBTC","ENGBTC","MDTBTC","PHBBTC","DATABTC","MANABTC","WABIBTC",
"VIBBTC","APPCBTC","BQXBTC","WTCBTC","BRDBTC","NEBLBTC","PERLBTC","WAVESBTC","MDABTC","FETBTC","ZENBTC","WANBTC",
"PPTBTC","STORJBTC","DOGEBTC","RDNBTC","XZCBTC","MTLBTC","MBLBTC","VIABTC","AEBTC","NAVBTC","XEMBTC",
"CVCBTC","AGIBTC","STRATBTC","STXBTC","COSBTC","EVXBTC","GNTBTC","LSKBTC","ELFBTC","KMDBTC","DCRBTC","VIBEBTC",
"CDTBTC","HOTBTC","GRSBTC","SNTBTC","TNTBTC","POABTC","DUSKBTC","RCNBTC","GXSBTC","DLTBTC","SNGLSBTC","QSPBTC",
"DNTBTC","SYSBTC","OSTBTC","PIVXBTC","ARPABTC","SNMBTC","WPRBTC","BCPTBTC","MITHBTC","HCBTC"];

export default coinList;